name: Create M3U Playlist

on:
  schedule:
    - cron: '0 7 * * *'  # This cron expression runs the workflow every day at midnight
  workflow_dispatch:  # Allows the workflow to be manually triggered

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script to generate M3U file
        run: |
          python generate_m3u.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add mytvfree.m3u
          git commit -m 'Update M3U playlist'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
